# Generated by Django 3.2.6 on 2021-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mobno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('aadharno', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dongle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=50)),
                ('dongleamount', models.CharField(max_length=50)),
                ('dongleofferdiscount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('postamount', models.CharField(max_length=50)),
                ('postvalidity', models.CharField(max_length=50)),
                ('postbenefits', models.CharField(max_length=50)),
                ('postofferdiscount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prename', models.CharField(max_length=50)),
                ('preamount', models.CharField(max_length=50)),
                ('prevalidity', models.CharField(max_length=50)),
                ('prebenefits', models.CharField(max_length=50)),
                ('preofferdiscount', models.CharField(max_length=50)),
            ],
        ),
    ]
