# Generated by Django 3.2.7 on 2021-09-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobno', models.CharField(max_length=50)),
                ('queryname', models.CharField(max_length=50)),
                ('querydes', models.CharField(max_length=100)),
                ('querysolution', models.CharField(default='solution will be provided by admin', max_length=50)),
            ],
        ),
    ]
