# Generated by Django 3.2.6 on 2021-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0002_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adhaarp',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='profilep',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
