# Generated by Django 3.2.6 on 2021-09-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0003_auto_20210906_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='dongle',
            name='donglebenefits',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dongle',
            name='typeofservices',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dongle',
            name='dongleofferdiscount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='postbenefits',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='postofferdiscount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='prebenefits',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='preofferdiscount',
            field=models.CharField(max_length=500),
        ),
    ]
