# Generated by Django 3.2.6 on 2021-09-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0004_auto_20210907_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dongle',
            name='donglevalidity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
