# Generated by Django 3.2.6 on 2021-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0005_dongle_donglevalidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongle',
            name='typeofservices',
            field=models.CharField(default='Prepaid', max_length=50),
        ),
    ]
