# Generated by Django 3.2.6 on 2021-09-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizFonica', '0006_alter_dongle_typeofservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongle',
            name='typeofservices',
            field=models.CharField(default='', max_length=50),
        ),
    ]
